wandb_version: 1

policy_type:
  desc: null
  value: MlpPolicy
total_timesteps:
  desc: null
  value: 1000000
env_id:
  desc: null
  value: <TimeLimit<RLBenchEnv<teodor_remove_from_zone-state-v0>>>
n_steps:
  desc: null
  value: 200
ent_coef:
  desc: null
  value: 0.01
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.16.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1713180561.0
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 16
      - 22
      - 23
      - 35
      4: 3.10.12
      5: 0.16.4
      8:
      - 5
      13: linux-x86_64
algo:
  desc: null
  value: PPO
policy_class:
  desc: null
  value: <class 'stable_baselines3.common.policies.ActorCriticPolicy'>
device:
  desc: null
  value: cpu
verbose:
  desc: null
  value: 1
policy_kwargs:
  desc: null
  value: '{}'
num_timesteps:
  desc: null
  value: 0
_total_timesteps:
  desc: null
  value: 1000000
_num_timesteps_at_start:
  desc: null
  value: 0
seed:
  desc: null
  value: None
action_noise:
  desc: null
  value: None
start_time:
  desc: null
  value: 1713180571435117050
learning_rate:
  desc: null
  value: 0.0003
tensorboard_log:
  desc: null
  value: runs/vpoltmdz
_last_obs:
  desc: null
  value: "[[ 1.00000000e+00 -2.86102295e-05  6.00814819e-04 -3.38554382e-04\n   1.10149384e-03\
    \ -2.00271606e-04 -3.71932983e-04 -3.33786011e-05\n  -3.33428216e-06  1.75599605e-01\
    \  7.48306775e-07 -8.73332918e-01\n   2.92113909e-05  1.22127914e+00  7.85388827e-01\
    \  4.17792425e-03\n   2.35302887e+01 -2.94500291e-02 -1.59879742e+01 -1.46075249e-01\n\
    \  -4.27752590e+00  2.84064598e-02  2.78654724e-01 -8.15664232e-03\n   1.47156954e+00\
    \ -8.12436883e-06  9.92719829e-01  2.53533312e-06\n   1.20446697e-01  3.99993807e-02\
    \  4.00000215e-02  1.77257950e-03\n  -4.37746930e-04  2.96533102e-07  1.77368824e-03\
    \  4.37672425e-04\n   9.83476625e-08  3.77386034e-01  1.07404124e-02  7.75002360e-01\n\
    \   1.67172730e-01 -5.19605279e-02  7.74996698e-01  3.53830874e-01\n   1.20728865e-01\
    \  7.75001705e-01  2.50000000e-01  0.00000000e+00\n   7.51999855e-01  2.50000000e-01\
    \  0.00000000e+00  7.51999855e-01]]"
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_original_obs:
  desc: null
  value: None
_episode_num:
  desc: null
  value: 0
use_sde:
  desc: null
  value: 'False'
sde_sample_freq:
  desc: null
  value: -1
_current_progress_remaining:
  desc: null
  value: 1.0
_stats_window_size:
  desc: null
  value: 100
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
_n_updates:
  desc: null
  value: 0
_custom_logger:
  desc: null
  value: 'False'
env:
  desc: null
  value: <stable_baselines3.common.vec_env.dummy_vec_env.DummyVecEnv object at 0x75e6ee735150>
_vec_normalize_env:
  desc: null
  value: None
observation_space:
  desc: null
  value: Box(-inf, inf, (52,), float32)
action_space:
  desc: null
  value: Box(-1.0, 1.0, (8,), float32)
n_envs:
  desc: null
  value: 1
gamma:
  desc: null
  value: 0.99
gae_lambda:
  desc: null
  value: 0.95
vf_coef:
  desc: null
  value: 0.5
max_grad_norm:
  desc: null
  value: 0.5
rollout_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.RolloutBuffer'>
rollout_buffer_kwargs:
  desc: null
  value: '{}'
batch_size:
  desc: null
  value: 64
n_epochs:
  desc: null
  value: 10
clip_range:
  desc: null
  value: <function constant_fn.<locals>.func at 0x75e6ef9f7910>
clip_range_vf:
  desc: null
  value: None
normalize_advantage:
  desc: null
  value: 'True'
target_kl:
  desc: null
  value: None
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x75e6ee74cd30>
rollout_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.RolloutBuffer object at 0x75e6ee735870>
policy:
  desc: null
  value: "ActorCriticPolicy(\n  (features_extractor): FlattenExtractor(\n    (flatten):\
    \ Flatten(start_dim=1, end_dim=-1)\n  )\n  (pi_features_extractor): FlattenExtractor(\n\
    \    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (vf_features_extractor):\
    \ FlattenExtractor(\n    (flatten): Flatten(start_dim=1, end_dim=-1)\n  )\n  (mlp_extractor):\
    \ MlpExtractor(\n    (policy_net): Sequential(\n      (0): Linear(in_features=52,\
    \ out_features=64, bias=True)\n      (1): Tanh()\n      (2): Linear(in_features=64,\
    \ out_features=64, bias=True)\n      (3): Tanh()\n    )\n    (value_net): Sequential(\n\
    \      (0): Linear(in_features=52, out_features=64, bias=True)\n      (1): Tanh()\n\
    \      (2): Linear(in_features=64, out_features=64, bias=True)\n      (3): Tanh()\n\
    \    )\n  )\n  (action_net): Linear(in_features=64, out_features=8, bias=True)\n\
    \  (value_net): Linear(in_features=64, out_features=1, bias=True)\n)"
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x75e717ea65c0>
